# 예약키를 Ctrl+Space 로 변경
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Ctrl+hjkl 로 pane 이동 (prefix 없이)
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# 기본 설정
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g history-limit 10000
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -sg escape-time 0

# 설정 리로드
bind r source-file ~/.tmux.conf \; display "Reloaded!"
